CREATE TABLE IF NOT EXISTS USERS(
    ID NUMERIC(38,0) PRIMARY KEY,
    LAST_UPDATE TIMESTAMP(6) NOT NULL ,
    CREATION_DATE TIMESTAMP(6) NOT NULL ,
    LOGIN VARCHAR(32),
    PASSWORD VARCHAR(32),
    E_MAIL VARCHAR(32)
);
CREATE TABLE IF NOT EXISTS TRACK(
    ID NUMERIC(38,0) PRIMARY KEY ,
    LAST_UPDATE TIMESTAMP(6) NOT NULL ,
    CREATION_DATE TIMESTAMP(6) NOT NULL ,
    TITLE VARCHAR(255) NOT NULL ,
    FILE_LINK VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MUSIC_FEATURE_TYPE(
    ID NUMERIC(38,0) PRIMARY KEY ,
    LAST_UPDATE TIMESTAMP(6) NOT NULL ,
    CREATION_DATE TIMESTAMP(6) NOT NULL ,
    TITLE VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS MUSIC_FEATURE(
    ID NUMERIC(38,0) PRIMARY KEY ,
    LAST_UPDATE TIMESTAMP(6) NOT NULL ,
    CREATION_DATE TIMESTAMP(6) NOT NULL ,
    MUSIC_FEATURE_TYPE_ID NUMERIC(38,0),
    TRACK_ID NUMERIC(38,0),
    VALUE VARCHAR(32) NOT NULL,
    CONSTRAINT FK_M_F_TYPE FOREIGN KEY (MUSIC_FEATURE_TYPE_ID) REFERENCES MUSIC_FEATURE_TYPE(ID),
    CONSTRAINT FK_TRACK FOREIGN KEY (TRACK_ID) REFERENCES TRACK(ID)
);

CREATE TABLE IF NOT EXISTS PLAYLIST(
    ID NUMERIC(38,0) PRIMARY KEY ,
    LAST_UPDATE TIMESTAMP(6) NOT NULL ,
    CREATION_DATE TIMESTAMP(6) NOT NULL ,
    TITLE VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS PLAYLIST_FEATURE_TYPE(
    ID NUMERIC(38,0) PRIMARY KEY ,
    LAST_UPDATE TIMESTAMP(6) NOT NULL ,
    CREATION_DATE TIMESTAMP(6) NOT NULL ,
    TITLE VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS PLAYLIST_FEATURE(
    ID NUMERIC(38,0) PRIMARY KEY ,
    LAST_UPDATE TIMESTAMP(6) NOT NULL ,
    CREATION_DATE TIMESTAMP(6) NOT NULL ,
    PLAYLIST_FEATURE_TYPE_ID NUMERIC(38,0),
    PLAYLIST_ID NUMERIC(38,0),
    VALUE VARCHAR(32) NOT NULL,
    CONSTRAINT PL_F_TYPE FOREIGN KEY (PLAYLIST_FEATURE_TYPE_ID) REFERENCES PLAYLIST_FEATURE_TYPE(ID),
    CONSTRAINT FK_P FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(ID)
);

CREATE TABLE IF NOT EXISTS ART_GROUP(
    ID NUMERIC(38,0) PRIMARY KEY ,
    LAST_UPDATE TIMESTAMP(6) NOT NULL ,
    CREATION_DATE TIMESTAMP(6) NOT NULL ,
    TITLE VARCHAR(32),
    LEADER_ID NUMERIC(38,0) NOT NULL,
    CONSTRAINT FK_LEAD FOREIGN KEY (LEADER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS GROUP_ARTISTS(
    ID NUMERIC(38,0) PRIMARY KEY,
    GROUP_ID NUMERIC(38,0) NOT NULL ,
    ARTIST_ID NUMERIC(38,0) NOT NULL ,
    CONSTRAINT FK_GR FOREIGN KEY (GROUP_ID) REFERENCES ART_GROUP(ID),
    CONSTRAINT FK_ARTIST FOREIGN KEY (ARTIST_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS CATEGORY(
    ID NUMERIC(38,0) PRIMARY KEY ,
    LAST_UPDATE TIMESTAMP(6) NOT NULL ,
    CREATION_DATE TIMESTAMP(6) NOT NULL ,
    TITLE VARCHAR(32)
);
CREATE TABLE IF NOT EXISTS TRACK_CATEGORY(
    ID NUMERIC(38,0) PRIMARY KEY ,
    TRACK_ID NUMERIC(38,0) NOT NULL ,
    CATEGORY_ID NUMERIC(38,0) NOT NULL,
    CONSTRAINT FK_TRACK FOREIGN KEY (TRACK_ID) REFERENCES TRACK(ID),
    CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE IF NOT EXISTS TRACK_IN_PLAYLIST(
    ID NUMERIC(38,0) PRIMARY KEY ,
    LAST_UPDATE TIMESTAMP(6) NOT NULL ,
    CREATION_DATE TIMESTAMP(6) NOT NULL ,
    TRACK_ID NUMERIC(38,0) NOT NULL ,
    PLAYLIST_ID NUMERIC(38,0) NOT NULL ,
    IS_DELETED NUMERIC(1),
    CONSTRAINT FK_TRACK FOREIGN KEY (TRACK_ID) REFERENCES TRACK(ID),
    CONSTRAINT FK_PLAYLIST FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(ID)
)