CREATE TABLE IF NOT EXISTS LIKES(
    ID int8 PRIMARY KEY,
    CREATION_DATE TIMESTAMP(6) NOT NULL ,
    USER_ID NUMERIC(38,0) NOT NULL ,
    ENTITY VARCHAR(32),
    ENTITY_ID NUMERIC(38,0) NOT NULL,
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    UNIQUE (USER_ID, ENTITY_ID)
);

CREATE TABLE IF NOT EXISTS join_user_bands(
    BAND_ID NUMERIC(38,0) NOT NULL ,
    USER_ID NUMERIC(38,0) NOT NULL ,
    CONSTRAINT FK_GR FOREIGN KEY (BAND_ID) REFERENCES app_band(ID),
    CONSTRAINT FK_ARTIST FOREIGN KEY (USER_ID) REFERENCES app_users(ID)
);

