CREATE TABLE IF NOT EXISTS ART_GROUP_TRACK(
    ID NUMERIC(38,0) PRIMARY KEY ,
    ART_GROUP_ID NUMERIC(38,0) NOT NULL ,
    TRACK_ID NUMERIC(38,0) NOT NULL ,
    CONSTRAINT FK_GROUP FOREIGN KEY (ART_GROUP_ID) REFERENCES art_group(ID),
    CONSTRAINT FK_TRACK FOREIGN KEY (TRACK_ID) REFERENCES track(ID),
    UNIQUE (ART_GROUP_ID, TRACK_ID)
)