spring:
  #Datasource
  datasource:
    #Embedded Tomcat
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  #Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
        format_sql: true
        show-sql: true
        max_fetch_depth: 20
        jdbc:
          fetch_size: 50
          batch_size: 10
#Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    ru:
      geekbrains:
        musicportal: DEBUG